### ISSUE TITLE
RFactor 2 - Problem with powerslide wheel slip effect

### ISSUE THREAD

**Issue by alexish657** [viper4gh/SimHub-Plugin-CalcLngWheelSlip#4]
Hey there, first of all, thanks a lot for your work, it's really appreciated since RF2 doesn't support transducer wheel slip effect. 

However, I got a little problem that may come from my side actually. I'm trying to achieve a result similar to the actual Wheel Slip effect in SimHub that is working with other game. Presently, I'm able to feel the Wheel lock effect no problem. However, I can't achieve a good result for the powerslide wheel slip effect. I want to feel the effect when the wheels are actually beginning to spin before I loose the car. Right now, the slip effect that I got, is when the car is completly side way and there is no possible way to save it.

**Comment by viper4gh** [comment]
Hi,
I checked the plugin in rFactor 2 and it works as it should.
The only problem was that one time the Detection Phase was completed directly after starting the session, which cannot be possible, because the car must move for this to happen. This happens only one time and for this case there is a controller action for the plugin in SimHub available for reseting it.
But now to your question:
The slip values are calculated correct, I calculate it with the values from the API. I cannot do anything more.
The question is, what we can do with it. I agree that the cars extremely oversteer already on low percentage values.
But the physics engine works this way. 
The only way I see is to work with the SimHub settings. 
I don't know what you already tested, but you can use custom shake effects, where you first set the NCalc Formula for every wheel (example Front Left, only wheel spin = negative LngWheelSlip values):
if([ViperDataPlugin.CalcLngWheelSlip.Computed.LngWheelSlip_FL]<0, ViperDataPlugin.CalcLngWheelSlip.Computed.LngWheelSlip_FL]*-100, 0)
And then change the response curve by higher the Minimum Force and set a Threshold.
Best way to fiddle around with the values: Record a short session in SimHub with rF2, then go to the Custom Effects in SimHub, start the Replay, because then you see directly the result of changing the response curve.

In my test video for AMS2 you see that there are values above 10% are needed, that the cars begins to oversteer:
https://www.youtube.com/watch?v=iKmRmxuBwxY
In rF2 the values are lower, but it is the same calculation. It is how the physics work in rF2.
