### ISSUE TITLE
Tyre Grip 

### ISSUE THREAD

**Issue by IIToxaII** [viper4gh/SimHub-Plugin-CalcLngWheelSlip#5]
Is there a way to calculate Tyre grip in ACC like in your video?

**Comment by IIToxaII** [comment]
Also there is Wheel Slip in ACC, is it only for Shakers? Or it can be used for telemetry?

**Comment by viper4gh** [comment]
> Is there a way to calculate Tyre grip in ACC like in your video?

Is it not working?
I don't really play ACC and I added support for it long time ago.
Further the plugin calculates slip values in drive direction only, not sideways. And that is exactly, what I want to reach with the plugin, because grip values in all directions is normally available in the game APIs.
But again I am not an expert for ACC and also not for the ACC API.

**Comment by viper4gh** [comment]
> Also there is Wheel Slip in ACC, is it only for Shakers? Or it can be used for telemetry?

I don't know.
I don't really play ACC and this is no support thread for the ACC API 😉
